using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
//Pet class that allows a pet to be created in portions of the project.
namespace GroomingSalonWebsite.Models
{
    public class Pet
    {
        //Basic petId that is autogenerated by the system
        public int PetId { get; set; }
        //Pets name that gets entered
        public String Name { get; set; }
        //Pets breed
        public String Breed { get; set; }

        //Made a float because most animals won't live past roughly 25-30 
        public float Age { get; set; }
        //Incase a pet is needed to be turned toString its actually a unique entering
        public override string ToString()
        {
            return Name + " " + Breed;
        }
    }
}
