using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
/// <summary>
/// Pet class that allows a pet to be created in portions of the project.
/// </summary>
namespace GroomingSalonWebsite.Models
{
    public class Pet
    {
        /// <summary>
        /// Basic petId that is autogenerated by the system
        /// </summary>
        public int PetId { get; set; }
        /// <summary>
        /// Pets name that gets entered
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// The type of breed that the pet is.
        /// </summary>
        public String Breed { get; set; }

        /// <summary>
        /// The pets age, made a float because most animals don't live past the age of 25-30
        /// </summary>
        public float Age { get; set; }
        /// <summary>
        /// Incase a pet is needed to be turned toString its actually a unique entering
        /// </summary>
        public override string ToString()
        {
            return Name + " " + Breed;
        }
    }
}
