using GroomingSalonWebsite.Data;
using GroomingSalonWebsite.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GroomingSalonWebsite.Controllers
{
    public class RescheduleController : Controller
    {
        private readonly SalonContext _context;
        //Create a logger for use later if need arises. Think it was autogenerated by the page.
        public RescheduleController(SalonContext context)
        {
            _context = context;
        }
        [HttpGet]
        public IActionResult RescheduleCancel()
        {
            Reschedule rescheduled = (from resched in _context.Reschedules where resched.Confirmation == true select resched).Include(nameof(Appointment)).FirstOrDefault();
            TempData["ApptDate"] = rescheduled.Appointment.ApptDate;
            rescheduled.Confirmation = false;
            return View();
        }
    }
}
